### ISSUE TITLE
Use AsNoTracking for EF

### ISSUE THREAD

**Issue by anpete** [ppanyukov/EntityFrameworkBenchmarks#1]
EF tracks query results by default, which incurs additional overhead because we need to take snapshots of entities as they are materialized.

Using AsNoTracking would be semantically closer to the Dapper and raw ADO examples.

**Comment by ppanyukov** [comment]
Interesting. I will rerun with this setting and report back. Thanks for pointing this out. Any quick links to docs will be appreciated too.

**Comment by ppanyukov** [comment]
So yes, this makes a difference.

It's about 2x faster with `AsNoTracking`. Still quite far from `dapper.net` but much better.

Post and benchmark code updated.
